[project]
name = "cds-portal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nicholas Earl", email = "contact@nicholasearl.me" }
]
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.0.1",
    "authlib>=1.5.2",
    "cds-dashboard",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "pydantic>=2.11.2",
    "python-dotenv>=1.1.0",
    "solara>=1.44.1",
    "solara-enterprise>=1.44.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cds-dashboard = { workspace = true }
cds-core = { workspace = true }
